[package]
name = "pepbut"
version = "0.1.0"
authors = ["Iliana Weller <ilianaw@buttslol.net>"]
license = "MIT/Apache-2.0"

[profile.release]
lto = true

[features]
nightly = []
pepbutd = ["lazy_static", "trust-dns-server"]

[[bin]]
name = "pepbutd"
required-features = ["pepbutd"]

[dependencies]
failure = "0.1"
lazy_static = { optional = true, version = "1.0" }
rmpv = "0.4"
trust-dns = { git = "https://github.com/bluejekyll/trust-dns", default-features = false }
trust-dns-server = { optional = true, git = "https://github.com/bluejekyll/trust-dns", default-features = false }
