[package]
name = "pepbut"
version = "0.1.0"
authors = ["Iliana Weller <ilianaw@buttslol.net>"]
license = "MIT/Apache-2.0"

[profile.release]
lto = true

[dependencies]
failure = "0.1"
idna = "0.1"
rmp = "0.8"

[dev-dependencies]
lazy_static = "1.0"
