[package]
name = "pepbut-json-api"
version = "0.1.0"
authors = ["iliana weller <ilianaw@buttslol.net>"]

[dependencies]
futures = "0.1"
hyper = { version = "0.12", default-features = false }
lazy_static = "1.0"
regex = "1.0"
serde_json = "1.0"
